name: React CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: set node version
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
        cache: 'npm'
    - name: clean cache
      run: npm cache clean --force

    - name: check node version
      run: node -v
    - name: check npm version
      run: npm -v
    - name: install dependencies
      run: npm install --no-package-lock 
      
    - name: run tests
      run: npm test -- --watchAll=false --coverage
      
    - name: Install Vercel CLI
      run: npm install --global vercel@canary
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
    - name: Build Project Artifacts
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}